version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-gradle:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "weekly"
    groups:
      all-npm:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: ["*"]


